import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar/Navbar";
import FirstNav from "@/components/FirstNav/FirstNav";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "react-hot-toast";
import MySession from "@/components/MySession/MySession";
import { getLoggedUserCart } from "./cart/cart.action";
import { getLoggedUserWishlist } from "./wishlist/wishlist.action";


const exo = Exo({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by omar mostafa",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {

  const cartData = await getLoggedUserCart()
  const wishListData = await getLoggedUserWishlist()
  return (
    <html lang="en" className={cn("antialiased", exo.variable)}>
      <body>
        <MySession>
          <FirstNav />
          <Navbar cart={cartData.numOfCartItems} wishList={wishListData.count} />
          {children}
          <Toaster position="top-center" reverseOrder={false} />
          <Footer />
        </MySession>
      </body>
    </html>
  );
}
